// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250405082534_UpdateData")]
    partial class UpdateData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("Domain.Entities.ComputerHardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HardwareId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ComputerId");

                    b.HasIndex("HardwareId");

                    b.ToTable("ComputerHardwares");
                });

            modelBuilder.Entity("Domain.Entities.Hardware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HardwareBrandId")
                        .HasColumnType("int");

                    b.Property<int>("HardwareDetailId")
                        .HasColumnType("int");

                    b.Property<int>("HardwareTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HardwareBrandId");

                    b.HasIndex("HardwareDetailId");

                    b.HasIndex("HardwareTypeId");

                    b.ToTable("Hardwares");
                });

            modelBuilder.Entity("Domain.Entities.HardwareBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HardwareTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HardwareTypeId");

                    b.ToTable("HardwareBrands");
                });

            modelBuilder.Entity("Domain.Entities.HardwareDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HardwareBrandId")
                        .HasColumnType("int");

                    b.Property<int>("HardwareTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HardwareBrandId");

                    b.HasIndex("HardwareTypeId");

                    b.ToTable("HardwareDetails");
                });

            modelBuilder.Entity("Domain.Entities.HardwareType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HardwareTypes");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeactive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserComputer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComputerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeactive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComputerID");

                    b.HasIndex("UserID");

                    b.ToTable("UserComputers");
                });

            modelBuilder.Entity("Domain.Entities.ComputerHardware", b =>
                {
                    b.HasOne("Domain.Entities.Computer", "Computer")
                        .WithMany("HardwareComponents")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hardware", "Hardware")
                        .WithMany()
                        .HasForeignKey("HardwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("Hardware");
                });

            modelBuilder.Entity("Domain.Entities.Hardware", b =>
                {
                    b.HasOne("Domain.Entities.HardwareBrand", "HardwareBrand")
                        .WithMany()
                        .HasForeignKey("HardwareBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HardwareDetail", "HardwareDetail")
                        .WithMany()
                        .HasForeignKey("HardwareDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HardwareType", "HardwareType")
                        .WithMany()
                        .HasForeignKey("HardwareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HardwareBrand");

                    b.Navigation("HardwareDetail");

                    b.Navigation("HardwareType");
                });

            modelBuilder.Entity("Domain.Entities.HardwareBrand", b =>
                {
                    b.HasOne("Domain.Entities.HardwareType", "hardwareType")
                        .WithMany("HardwareBrand")
                        .HasForeignKey("HardwareTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("hardwareType");
                });

            modelBuilder.Entity("Domain.Entities.HardwareDetail", b =>
                {
                    b.HasOne("Domain.Entities.HardwareBrand", "HardwareBrand")
                        .WithMany("HardwareDetail")
                        .HasForeignKey("HardwareBrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HardwareType", "HardwareType")
                        .WithMany("HardwareDetail")
                        .HasForeignKey("HardwareTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HardwareBrand");

                    b.Navigation("HardwareType");
                });

            modelBuilder.Entity("Domain.Entities.UserComputer", b =>
                {
                    b.HasOne("Domain.Entities.Computer", "Computer")
                        .WithMany("UserComputer")
                        .HasForeignKey("ComputerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Computer", b =>
                {
                    b.Navigation("HardwareComponents");

                    b.Navigation("UserComputer");
                });

            modelBuilder.Entity("Domain.Entities.HardwareBrand", b =>
                {
                    b.Navigation("HardwareDetail");
                });

            modelBuilder.Entity("Domain.Entities.HardwareType", b =>
                {
                    b.Navigation("HardwareBrand");

                    b.Navigation("HardwareDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
